# Autocomplete support
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
if type brew 2&>/dev/null; then
  source "$(brew --prefix)/etc/bash_completion"
fi
if [ -d $HOME/.phabricator ]; then
  source $HOME/.phabricator/arcanist/resources/shell/bash-completion
fi

# Set up fzf key bindings and fuzzy completion
if [ $(command -v fzf) ]; then
  eval "$(fzf --bash)"
fi

# Prompt configuration
if [ -f "/usr/local/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR="/usr/local/opt/bash-git-prompt/share"
  source "/usr/local/opt/bash-git-prompt/share/gitprompt.sh"
  export GIT_PS1_SHOWUPSTREAM="auto"
  # export GIT_PS1_SHOWUNTRACKEDFILES=1
  # export GIT_PS1_SHOWSTASHSTATE=1
  export GIT_PS1_SHOWDIRTYSTATE=1
  export GIT_PS1_SHOWCOLORHINTS=1
  if [ "$(type -t update_terminal_cwd)" = 'function' ]; then
    export PROMPT_COMMAND='__git_ps1 "\h:\W \u" "\$"&&update_terminal_cwd'
  else
    export PROMPT_COMMAND='__git_ps1 "\h:\W \u" "\$"'
  fi
fi

if [ -f $HOME/.bashrc_extra ]; then
  source $HOME/.bashrc_extra
fi

if [ -f $HOME/.interactive ]; then
  source $HOME/.interactive
fi
