# Pure prompt support
fpath+=$HOME/.dotfiles/zsh_plugins/pure
autoload -U promptinit
promptinit

# Customise pure prompt
PURE_PROMPT_SYMBOL="%%"
PURE_GIT_PULL=0
zstyle :prompt:pure:git:stash show yes

prompt pure

# Autocomplete support
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

autoload -U compinit
compinit

source $HOME/.dotfiles/zsh_plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

if [ -f $HOME/.interactive ]; then
  source $HOME/.interactive
fi

# Syntax highlighting support
# Note this must be sourced at the end of .zshrc
source $HOME/.dotfiles/zsh_plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
