# Pure prompt support
fpath+=~/.dotfiles/zsh_plugins/pure
autoload -U promptinit
promptinit

# Customise pure prompt
PURE_PROMPT_SYMBOL="%%"

prompt pure

# Autocomplete support
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

autoload -U compinit
compinit

source ~/.dotfiles/zsh_plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

if [ -f ~/.interactive ]; then
  source ~/.interactive
fi

# Syntax highlighting support
# Note this must be sourced at the end of .zshrc
source ~/.dotfiles/zsh_plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
