# Autocomplete support
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

autoload -U compinit
compinit

source ~/.dotfiles/zsh_plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

if [ -f ~/.interactive ]; then
  source ~/.interactive
fi
